# Generated by Django 4.1.7 on 2023-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField(null=True)),
                ('bsched_id', models.IntegerField(null=True)),
                ('region_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=191)),
                ('whscode', models.CharField(max_length=191, null=True)),
                ('bm_oic', models.CharField(max_length=191, null=True)),
                ('contact', models.CharField(max_length=191, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('address', models.CharField(max_length=191)),
                ('contact', models.CharField(max_length=191, null=True)),
                ('email', models.CharField(max_length=191, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'divisions',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=191, null=True)),
                ('file', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('from_field', models.IntegerField(db_column='from', null=True)),
                ('to', models.IntegerField(null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('po_accesschart_id', models.IntegerField(null=True)),
                ('remarks_by', models.IntegerField(null=True)),
                ('remarks2', models.TextField(null=True)),
                ('waiting_for', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('po_number', models.IntegerField(null=True)),
                ('type_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserEmployments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sss', models.IntegerField(null=True)),
                ('user_id', models.PositiveIntegerField()),
                ('division_id', models.PositiveIntegerField(null=True)),
                ('department_id', models.PositiveIntegerField(null=True)),
                ('position_id', models.PositiveIntegerField(null=True)),
                ('accesschart_id', models.PositiveIntegerField(null=True)),
                ('branch_id', models.PositiveIntegerField(null=True)),
                ('payroll', models.IntegerField(null=True)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('remarks', models.CharField(max_length=191, null=True)),
                ('last_date_reported', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mrf_accesschart_id', models.PositiveIntegerField(null=True)),
                ('po_file_accesschart_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'user_employments',
            },
        ),
    ]
